### PR TITLE
Dereference JSON Schema for message bodies

### PR DESCRIPTION
**Pull request by smizell**
This dereferences JSON Schemas in the message bodies so that Apiary will use the JSON Schemas correctly. 

**Note**: It adds a new dependency.

### CODE REVIEW

**Comment by smizell** [comment]
Also, another note, this only dereferences local references. References can be over the web, and this will not handle that. There is an asynchronous version of the library I'm using that I'll incorporate once we clean up the code.

This may be something to mention in the Fury/Swagger2Blueprint README.

**Comment by smizell** [comment]
Latest commit adds a try/catch to ensure `deref` works OK. Also, path values can have other values than methods, so I strip those out for now. Will handle later (maybe in another commit).

**Comment by smizell** [comment]
Leaving this PR as is. Will add other support in another PR.

**Comment by danielgtaylor** [comment]
Looks good, thanks!

**Pull request merged**
