### PR TITLE
 Use deckardcain library to identify source code in legacy interface

### PR DESCRIPTION
**Pull request by honzajavorek**
Follow-up to #46.

Please note this is PR into a new branch called `shared/integration`.

---
- Using [Deckard Cain](https://github.com/apiaryio/deckardcain) for identifying ambiguous source code.
- Removed `newVersionRegExp` from the interface (will need additional changes in Apiary codebase once we will upgrade the core application to Fury version containing changes in this PR).
- Removed some tests as they were testing the same stuff which is already tested in Deckard's tests.

### CODE REVIEW

**Comment by honzajavorek** [comment]
@Baggz @zdne According to what was agreed, I created `shared/integration` branch and I sent this first PR. I assume this branch is owned by The Core Application team and thus @ttahmouch has the final word in reviews, which could help us to move faster. That, of course, doesn't mean Blueprint team cannot make comments and suggestions.

**Comment by pksunkara** [comment]
Reviewed. lgtm.

**Comment by ttahmouch** [comment]
@honzajavorek 
Reviewed. LGTM as well.

**Comment by honzajavorek** [comment]
Thanks!

**Comment by honzajavorek** [comment]
@Baggz @apiaryio/api-blueprint 

**FYI:** We created [our own fork](https://github.com/apiaryio/fury.js-integration) for the purpose of integration as Fury.js code needs to be published (it's compiled and it can't be installed directly from Git branch). We will work on the fork in short iterations and it is going to be published and used as a package in our private npm repository. Once the integration period is over, we are going to send a proper separate PR on this repository, which will remove the legacy interface from Fury.js.

We are not going to use the `shared/integration` branch for anything now, so feel free to delete it.

**Comment by pksunkara** [comment]
@honzajavorek Why don't you guys use shared/integration branch like how we use shared/refract branch in protagonist?

**Comment by honzajavorek** [comment]
@pksunkara Because this way our processes do not interfere with yours. Flexibility and safety. We can prepare the whole thing within our team, it's easier not to make a mistake in publishing the package, it's under our full control and we can do all sorts of stuff and experimenting with Fury without affecting the original Open Source repository.

**Comment by danielgtaylor** [comment]
@honzajavorek does this mean I can remove the CoffeeScript files from Fury.js?

**Comment by honzajavorek** [comment]
@danielgtaylor Not yet! Eventually, yes, this action should lead to it. Eventually :-)

**Pull request merged**
