### PR TITLE
markdown typo fix

### PR DESCRIPTION
**Pull request by m-baumgartner**

### CODE REVIEW

**Comment by pksunkara** [comment]
:+1: Retrying the CI again.

**Comment by pksunkara** [comment]
@danielgtaylor Looks like coveralls is complaining that it can't find fury.js repo.

**Comment by m-baumgartner** [comment]
How could this fix break anything ?! ^^

**Comment by danielgtaylor** [comment]
@m-baumgartner this fix isn't breaking anything. The testing server is unable to report the updated coverage to our code coverage service. Since the tests pass and I'm guessing this is just a temporary issue with the code coverage service, I'm going to merge this in. Thanks for the fix!

**Pull request merged**
