### PR TITLE
Update to Minim 0.9.x.

### PR DESCRIPTION
**Pull request by danielgtaylor**
This change depends on refractproject/minim#55 and refractproject/minim#66. It
updates Fury to use the latest and greatest interface to refract elements,
including updating the refract API namespace elements, the API Blueprint
serializer, and the Swagger parser.

cc @zdne @kylef @pksunkara @smizell

### CODE REVIEW

**Comment by zdne** [comment]
@danielgtaylor Tests failed :crying_cat_face:

**Comment by danielgtaylor** [comment]
@zdne yeah it depends on those other pull requests mentioned above being merged first :wink:

**Comment by pksunkara** [comment]
Is this PR good to go since the other PRs are merged?

**Comment by danielgtaylor** [comment]
@pksunkara we need to do a release of Minim first, but then yes it should be ready to go.

**Comment by danielgtaylor** [comment]
@pksunkara this should now be safe to merge.

**Pull request merged**
